# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
      timezone: 'Europe/Berlin'
    assignees: 
      - 'freakyDude' 
    groups:
      npm-security-updates:
        applies-to: security-updates
        update-types:
          - 'minor'
          - 'patch'
      npm-minor-updates:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
      npm-major-updates:
        applies-to: version-updates
        update-types:
          - 'major'          
  - package-ecosystem: 'cargo' # See documentation for possible values
    directory: '/src-tauri' # Location of package manifests
    assignees: 
      - 'freakyDude' 
    schedule:
      interval: 'weekly'
      timezone: 'Europe/Berlin'
    groups:
      cargo-security-updates:
        applies-to: security-updates
        update-types:
          - 'minor'
          - 'patch'
      cargo-minor-updates:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
      cargo-major-updates:
        applies-to: version-updates
        update-types:
          - 'major'          
  - package-ecosystem: 'github-actions'
    directory: '/'
    assignees: 
      - 'freakyDude' 
    schedule:
      interval: 'weekly'
      timezone: 'Europe/Berlin'